import type { PlanState, Scenario, PlanEvent, Decision, Goal } from "../types";

const nowYear = new Date().getFullYear();

const baseAssumptions = {
  inflation: 0.03,
  investmentReturn: 0.065,
  savingsRate: 0.22,
  currentAge: 39,
  targetRetirementAge: 57,
  currentNetWorth: 620_000,
  annualNetIncome: 145_000,
  annualExpenses: 96_000,
};

const scenarios: Scenario[] = [
  {
    id: "current",
    name: "Current Plan",
    description: "Life on your current trajectory.",
    assumptions: { ...baseAssumptions },
    eventIds: ["e-home", "e-school", "e-exit", "e-semi", "e-retire"],
    decisionIds: [],
    goalIds: ["g-fi", "g-edu", "g-holiday", "g-legacy", "g-norseman"],
  },
  {
    id: "early-retirement",
    name: "Early Retirement",
    description: "Retire five years earlier by trimming lifestyle inflation.",
    assumptions: {
      ...baseAssumptions,
      targetRetirementAge: 52,
      savingsRate: 0.32,
      annualExpenses: 82_000,
    },
    eventIds: ["e-home", "e-school", "e-exit", "e-retire-early"],
    decisionIds: [],
    goalIds: ["g-fi", "g-edu", "g-holiday"],
  },
  {
    id: "italy",
    name: "Move to Italy",
    description: "Relocate to Puglia in 2032. Different costs, different tax.",
    assumptions: {
      ...baseAssumptions,
      annualExpenses: 72_000,
      annualNetIncome: 110_000,
    },
    eventIds: ["e-home", "e-school", "e-move-italy", "e-retire"],
    decisionIds: [],
    goalIds: ["g-fi", "g-edu", "g-holiday", "g-legacy"],
  },
  {
    id: "entrepreneur",
    name: "Entrepreneur",
    description: "Buy a company, grow it, exit in 2037.",
    assumptions: {
      ...baseAssumptions,
      annualNetIncome: 170_000,
      savingsRate: 0.28,
    },
    eventIds: ["e-home", "e-school", "e-acquire", "e-exit-big", "e-retire"],
    decisionIds: [],
    goalIds: ["g-fi", "g-edu", "g-legacy", "g-buy-company"],
  },
];

const events: PlanEvent[] = [
  {
    id: "e-home",
    title: "Buy family home",
    type: "home_purchase",
    date: `${nowYear + 1}-06-01`,
    probability: 0.9,
    status: "planned",
    scenarioId: "current",
    effects: [
      {
        id: "e-home-cash",
        eventId: "e-home",
        kind: "cash_delta",
        amount: -180_000,
        frequency: "one_off",
        startYear: nowYear + 1,
        label: "Deposit & fees",
      },
      {
        id: "e-home-asset",
        eventId: "e-home",
        kind: "asset_delta",
        amount: 950_000,
        frequency: "one_off",
        startYear: nowYear + 1,
        label: "Property added",
      },
      {
        id: "e-home-liab",
        eventId: "e-home",
        kind: "liability_delta",
        amount: 770_000,
        frequency: "one_off",
        startYear: nowYear + 1,
        label: "Mortgage",
      },
    ],
  },
  {
    id: "e-school",
    title: "Charlotte starts school",
    type: "education",
    date: `${nowYear + 2}-09-01`,
    probability: 1,
    status: "confirmed",
    scenarioId: "current",
    effects: [
      {
        id: "e-school-cost",
        eventId: "e-school",
        kind: "recurring_expense",
        amount: 1_650,
        frequency: "monthly",
        startYear: nowYear + 2,
        endYear: nowYear + 15,
        label: "School fees",
      },
    ],
  },
  {
    id: "e-exit",
    title: "Business exit",
    type: "business_sale",
    date: `${nowYear + 9}-03-01`,
    probability: 0.6,
    status: "planned",
    scenarioId: "current",
    effects: [
      {
        id: "e-exit-cash",
        eventId: "e-exit",
        kind: "cash_delta",
        amount: 1_200_000,
        frequency: "one_off",
        startYear: nowYear + 9,
        label: "Net proceeds",
      },
    ],
  },
  {
    id: "e-semi",
    title: "Semi-retirement",
    type: "semi_retirement",
    date: `${nowYear + 14}-01-01`,
    probability: 0.85,
    status: "planned",
    scenarioId: "current",
    effects: [
      {
        id: "e-semi-salary",
        eventId: "e-semi",
        kind: "salary_delta",
        amount: -40_000,
        frequency: "annual",
        startYear: nowYear + 14,
        endYear: nowYear + 18,
        label: "Reduced hours",
      },
    ],
  },
  {
    id: "e-retire",
    title: "Full retirement",
    type: "retirement",
    date: `${nowYear + 18}-01-01`,
    probability: 0.9,
    status: "planned",
    scenarioId: "current",
    effects: [],
  },
  {
    id: "e-retire-early",
    title: "Full retirement",
    type: "retirement",
    date: `${nowYear + 13}-01-01`,
    probability: 0.8,
    status: "planned",
    scenarioId: "early-retirement",
    effects: [],
  },
  {
    id: "e-move-italy",
    title: "Move to Puglia",
    type: "move_abroad",
    date: `${nowYear + 8}-07-01`,
    probability: 0.7,
    status: "planned",
    scenarioId: "italy",
    effects: [
      {
        id: "italy-cost",
        eventId: "e-move-italy",
        kind: "recurring_expense",
        amount: -1_500,
        frequency: "monthly",
        startYear: nowYear + 8,
        label: "Lower cost of living",
      },
    ],
  },
  {
    id: "e-acquire",
    title: "Acquire company",
    type: "business_acquisition",
    date: `${nowYear + 2}-01-01`,
    probability: 0.7,
    status: "planned",
    scenarioId: "entrepreneur",
    effects: [
      {
        id: "acq-cash",
        eventId: "e-acquire",
        kind: "cash_delta",
        amount: -250_000,
        frequency: "one_off",
        startYear: nowYear + 2,
        label: "Equity contribution",
      },
    ],
  },
  {
    id: "e-exit-big",
    title: "Exit company",
    type: "business_sale",
    date: `${nowYear + 13}-06-01`,
    probability: 0.55,
    status: "planned",
    scenarioId: "entrepreneur",
    effects: [
      {
        id: "exit-big-cash",
        eventId: "e-exit-big",
        kind: "cash_delta",
        amount: 3_400_000,
        frequency: "one_off",
        startYear: nowYear + 13,
        label: "Net proceeds",
      },
    ],
  },
];

const goals: Goal[] = [
  {
    id: "g-fi",
    title: "Financial Independence",
    targetDate: `${nowYear + 18}-01-01`,
    targetAmount: 2_400_000,
    priority: "must",
    progress: 0.28,
    confidence: "on_track",
    description: "Work becomes optional.",
  },
  {
    id: "g-edu",
    title: "Charlotte & Victoria's education",
    targetDate: `${nowYear + 18}-01-01`,
    targetAmount: 320_000,
    priority: "must",
    progress: 0.1,
    confidence: "on_track",
  },
  {
    id: "g-holiday",
    title: "Holiday home in Puglia",
    targetDate: `${nowYear + 10}-06-01`,
    targetAmount: 450_000,
    priority: "want",
    progress: 0.05,
    confidence: "at_risk",
  },
  {
    id: "g-legacy",
    title: "Leave £2M legacy",
    targetDate: `${nowYear + 40}-01-01`,
    targetAmount: 2_000_000,
    priority: "wish",
    progress: 0.31,
    confidence: "on_track",
  },
  {
    id: "g-norseman",
    title: "Complete Norseman",
    targetDate: `${nowYear + 3}-08-01`,
    priority: "want",
    progress: 0.4,
    confidence: "on_track",
    description: "Because life isn't only money.",
  },
  {
    id: "g-buy-company",
    title: "Own a company",
    targetDate: `${nowYear + 2}-01-01`,
    priority: "want",
    progress: 0.6,
    confidence: "on_track",
  },
];

const decisions: Decision[] = [
  {
    id: "d-4day",
    title: "Reduce to a four-day week",
    category: "career",
    description: "Trade ~15% of income for one day back each week.",
    status: "considering",
    createdAt: new Date().toISOString(),
    eventIds: [],
    expectedImpact: "Delays FI by roughly 14 months.",
  },
  {
    id: "d-puglia",
    title: "Buy holiday home in Puglia",
    category: "housing",
    description: "€380k stone trullo, 45 mins from the coast.",
    status: "considering",
    createdAt: new Date().toISOString(),
    eventIds: [],
    expectedImpact: "Uses £120k cash and adds €900/mo running costs.",
  },
  {
    id: "d-pension",
    title: "Increase pension by £500/month",
    category: "investing",
    description: "Redirect part of Andrea's bonus into SIPP.",
    status: "considering",
    createdAt: new Date().toISOString(),
    eventIds: [],
    expectedImpact: "Brings FI forward by ~11 months.",
  },
];

export const seedPlanState: PlanState = {
  scenarios,
  events,
  decisions,
  goals,
  activeScenarioId: "current",
};
